# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15OuwCYEa1od7LZxVTBOvYoK-l8Jg4Q97
"""

import streamlit as st
import pandas as pd
from fpdf import FPDF
from datetime import datetime
import tempfile
import os

# ==============================================================================
# 1. CONFIGURAÇÃO E DADOS PADRÃO (SÓ USADOS NA 1ª VEZ)
# ==============================================================================

st.set_page_config(page_title="Gerador de Orçamento Pro", page_icon="🛠️", layout="wide")

# Nomes dos arquivos onde os dados serão salvos
FILES = {
    "Materiais": "db_materiais.csv",
    "MaoDeObra": "db_mdo.csv",
    "Kits": "db_kits.csv",
    "Config_Acionamentos": "db_conf_acion.csv",
    "Config_Vasos": "db_conf_vasos.csv",
    "Config_Hidraulica": "db_conf_hidra.csv"
}

# Dados iniciais (para criar os arquivos se não existirem)
DEFAULT_DATA = {
    "Materiais": {
        'ID_Material': ['CLP-AUT-01', 'CLP-AUT-02', 'PAINEL-8060', 'PAINEL-10060', 'CONT-MOT-12A', 'RELE-INT-24V', 'VASO-FIL-3072', 'VALV-BORB-E4', 'TUBO-PVC-4', 'CURVA-PVC-90-4', 'MEDIA-ZEO-25'],
        'Descricao': ['CLP Básico', 'CLP Avançado', 'Painel 80x60', 'Painel 100x60', 'Contator 12A', 'Relé 24V', 'Vaso 30x72', 'Válvula Borboleta 4"', 'Tubo PVC 4"', 'Curva 90 PVC 4"', 'Zeolita 25kg'],
        'Grupo_Orcamento': ['CLP', 'CLP', 'Painel', 'Painel', 'Painel', 'Painel', 'Vasos', 'Hidráulica', 'Hidráulica', 'Hidráulica', 'Hidráulica'],
        'Preco_Custo': [2500.0, 4500.0, 750.0, 950.0, 90.0, 40.0, 6000.0, 1200.0, 210.0, 28.0, 110.0]
    },
    "MaoDeObra": {
        'ID_MaoDeObra': ['MDO-MONT-ELET', 'MDO-PROG-CLP', 'MDO-MONT-HIDR'],
        'Tipo_Servico': ['Montagem Elétrica', 'Programação CLP', 'Montagem Hidráulica'],
        'Custo_Hora': [80.0, 150.0, 70.0]
    },
    "Kits": {
        'ID_Kit': ['KIT-PAINEL-1V', 'KIT-PAINEL-1V', 'KIT-HID-4872-PV-100MM', 'KIT-HID-4872-PV-100MM'],
        'ID_Material': ['CONT-MOT-12A', 'RELE-INT-24V', 'VALV-BORB-E4', 'CURVA-PVC-90-4'],
        'Quantidade': [6, 6, 6, 12]
    },
    "Config_Acionamentos": {
        'Num_Vasos': [1, 2, 3, 4],
        'ID_Material_CLP': ['CLP-AUT-01', 'CLP-AUT-01', 'CLP-AUT-02', 'CLP-AUT-02'],
        'ID_Material_Painel': ['PAINEL-8060', 'PAINEL-8060', 'PAINEL-10060', 'PAINEL-10080'],
        'ID_Material_IHM': ['IHM-AUT-7POL', 'IHM-AUT-7POL', 'IHM-AUT-10POL', 'IHM-AUT-10POL'],
        'ID_Kit_Painel_Eletrico': ['KIT-PAINEL-1V', 'KIT-PAINEL-2V', 'KIT-PAINEL-3V', 'KIT-PAINEL-4V'],
        'Horas_MDO_Mont_Elet': [16, 24, 32, 40],
        'Horas_MDO_Prog_CLP': [10, 16, 24, 30]
    },
    "Config_Vasos": {
        'Descricao_Vaso': ['30x72', '36x72', '42x72', '48x72', '63x80'],
        'ID_Material_Vaso': ['VASO-FIL-3072', 'VASO-FIL-3672', 'VASO-FIL-4272', 'VASO-FIL-4872', 'VASO-FIL-6380'],
        'Horas_MDO_Hidr_p_Vaso': [16, 18, 20, 22, 25]
    },
    "Config_Hidraulica": {
        'Descricao_Vaso': ['48x72'],
        'ID_Diametro_mm': [100],
        'ID_Kit_Hidraulico_p_Vaso': ['KIT-HID-4872-PV-100MM']
    }
}

# Função para carregar ou criar dados
def load_data():
    dataframes = {}
    for key, filename in FILES.items():
        if os.path.exists(filename):
            # Lê do arquivo se existir
            dataframes[key] = pd.read_csv(filename)
        else:
            # Cria do padrão se não existir
            df = pd.DataFrame(DEFAULT_DATA.get(key, {}))
            df.to_csv(filename, index=False)
            dataframes[key] = df
    return dataframes

# Função para salvar dados
def save_data(key, df):
    filename = FILES[key]
    df.to_csv(filename, index=False)
    st.success(f"Dados de {key} salvos com sucesso em {filename}!")

# Carrega tudo na memória
db = load_data()

# ==============================================================================
# 2. LÓGICA DE CÁLCULO (MESMA DE ANTES, MAS USANDO 'db')
# ==============================================================================
def calcular_orcamento(num_vasos, tam_vaso, diametro, margem):
    df_materiais = db["Materiais"]
    df_mdo = db["MaoDeObra"]
    df_kits = db["Kits"]
    df_conf_acion = db["Config_Acionamentos"]
    df_conf_vasos = db["Config_Vasos"]
    df_conf_hidra = db["Config_Hidraulica"]

    # Busca Regras
    try:
        regra_painel = df_conf_acion[df_conf_acion['Num_Vasos'] == num_vasos].iloc[0]
        regra_vaso = df_conf_vasos[df_conf_vasos['Descricao_Vaso'] == tam_vaso].iloc[0]

        filtro_hid = (df_conf_hidra['Descricao_Vaso'] == tam_vaso) & (df_conf_hidra['ID_Diametro_mm'] == diametro)
        if filtro_hid.sum() == 0:
            return None, "❌ Configuração Hidráulica não cadastrada no banco de dados."

        id_kit_hidra = df_conf_hidra[filtro_hid].iloc[0]['ID_Kit_Hidraulico_p_Vaso']
        id_kit_painel = regra_painel['ID_Kit_Painel_Eletrico']
    except IndexError:
        return None, "❌ Erro ao buscar regras. Verifique se o vaso/painel está cadastrado nas abas de Configuração."

    itens = []
    # Itens Soltos
    itens.append({'ID': regra_painel['ID_Material_CLP'], 'Qtd': 1, 'Tipo': 'Material'})
    itens.append({'ID': regra_painel['ID_Material_Painel'], 'Qtd': 1, 'Tipo': 'Material'})
    itens.append({'ID': regra_painel['ID_Material_IHM'], 'Qtd': 1, 'Tipo': 'Material'})
    itens.append({'ID': regra_vaso['ID_Material_Vaso'], 'Qtd': num_vasos, 'Tipo': 'Material'})

    # Kit Painel
    kit_painel_itens = df_kits[df_kits['ID_Kit'] == id_kit_painel]
    if kit_painel_itens.empty: st.warning(f"⚠️ Atenção: O {id_kit_painel} não tem itens cadastrados na aba Kits.")
    for _, row in kit_painel_itens.iterrows():
        itens.append({'ID': row['ID_Material'], 'Qtd': row['Quantidade'], 'Tipo': 'Material'})

    # Kit Hidráulica
    kit_hid_itens = df_kits[df_kits['ID_Kit'] == id_kit_hidra]
    if kit_hid_itens.empty: st.warning(f"⚠️ Atenção: O {id_kit_hidra} não tem itens cadastrados na aba Kits.")
    for _, row in kit_hid_itens.iterrows():
        itens.append({'ID': row['ID_Material'], 'Qtd': row['Quantidade'] * num_vasos, 'Tipo': 'Material'})

    # Mão de Obra
    itens.append({'ID': 'MDO-MONT-ELET', 'Qtd': regra_painel['Horas_MDO_Mont_Elet'], 'Tipo': 'MDO'})
    itens.append({'ID': 'MDO-PROG-CLP', 'Qtd': regra_painel['Horas_MDO_Prog_CLP'], 'Tipo': 'MDO'})
    itens.append({'ID': 'MDO-MONT-HIDR', 'Qtd': regra_vaso['Horas_MDO_Hidr_p_Vaso'] * num_vasos, 'Tipo': 'MDO'})

    resultado = []
    total = 0

    for item in itens:
        if item['Tipo'] == 'Material':
            dados = df_materiais[df_materiais['ID_Material'] == item['ID']]
            if dados.empty:
                st.error(f"Item {item['ID']} não encontrado no cadastro de Materiais!")
                continue
            desc = dados.iloc[0]['Descricao']
            custo = float(dados.iloc[0]['Preco_Custo'])
        else:
            dados = df_mdo[df_mdo['ID_MaoDeObra'] == item['ID']]
            if dados.empty: continue
            desc = dados.iloc[0]['Tipo_Servico']
            custo = float(dados.iloc[0]['Custo_Hora'])

        preco_final = custo * (1 + margem) * item['Qtd']
        resultado.append({
            'Código': item['ID'], 'Descrição': desc, 'Qtd': item['Qtd'],
            'Custo Unit': custo, 'Venda Total': preco_final
        })
        total += preco_final

    return pd.DataFrame(resultado), total

# ==============================================================================
# 3. INTERFACE COM ABAS
# ==============================================================================

tab1, tab2 = st.tabs(["💰 Calculadora de Orçamento", "🛠️ Editor de Dados (Admin)"])

# --- ABA 1: CALCULADORA ---
with tab1:
    st.header("Novo Orçamento")

    col1, col2, col3 = st.columns(3)
    with col1:
        sel_vasos = st.selectbox("Número de Vasos", db["Config_Acionamentos"]['Num_Vasos'].unique())
    with col2:
        sel_tamanho = st.selectbox("Tamanho do Vaso", db["Config_Vasos"]['Descricao_Vaso'].unique())
    with col3:
        sel_diametro = st.selectbox("Diâmetro", db["Config_Hidraulica"]['ID_Diametro_mm'].unique())

    sel_margem = st.slider("Margem de Lucro (%)", 0, 100, 50) / 100

    if st.button("Calcular Valor", type="primary"):
        df_res, total = calcular_orcamento(sel_vasos, sel_tamanho, sel_diametro, sel_margem)

        if isinstance(total, str):
            st.error(total)
        else:
            st.success(f"### Valor Total: R$ {total:,.2f}")
            st.dataframe(df_res, use_container_width=True)

            # Gerador de PDF (Simples)
            class PDF(FPDF):
                def header(self):
                    self.set_font('Arial', 'B', 14)
                    self.cell(0, 10, 'Orcamento Comercial', 0, 1, 'C')

            if st.button("Gerar PDF"):
                pdf = PDF()
                pdf.add_page()
                pdf.set_font("Arial", size=12)
                pdf.cell(0, 10, f"Data: {datetime.now().strftime('%d/%m/%Y')}", 0, 1)
                pdf.cell(0, 10, f"Total: R$ {total:,.2f}", 0, 1)
                pdf.ln(5)
                # Tabela simples
                for i, row in df_res.iterrows():
                    pdf.cell(0, 10, f"{row['Qtd']}x {row['Descrição']} - R$ {row['Venda Total']:,.2f}", 0, 1)

                temp = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
                pdf.output(temp.name)
                with open(temp.name, "rb") as f:
                    st.download_button("📥 Baixar PDF", f, "orcamento.pdf")

# --- ABA 2: EDITOR (A MÁGICA ACONTECE AQUI) ---
with tab2:
    st.header("Gerenciador de Banco de Dados")
    st.info("Edite os valores abaixo. As alterações são salvas automaticamente nos arquivos CSV quando você clica em 'Salvar Alterações'.")

    opcao = st.selectbox("Qual tabela você quer editar?", list(FILES.keys()))

    # Carrega o DF atual
    df_atual = db[opcao]

    # Mostra o editor (permite adicionar linhas com num_rows="dynamic")
    df_editado = st.data_editor(df_atual, num_rows="dynamic", use_container_width=True)

    if st.button(f"💾 Salvar Alterações em {opcao}"):
        save_data(opcao, df_editado)
        # Recarrega a página para atualizar os dados na memória
        st.rerun()